version: 2

jobs:
  build:
    macos:
      xcode: "9.2.0"
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run: echo "2.3.5" > .ruby-version
      - run: bundle install --path .bundle
      - run:
          name: Install CocoaPods
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            pod install
      - run: bundle exec fastlane ci
